# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
data:
  cert_policy_controller: quay.io/open-cluster-management/cert-policy-controller:latest
  config_policy_controller: quay.io/open-cluster-management/config-policy-controller:latest
  governance_policy_propagator: quay.io/open-cluster-management/governance-policy-propagator:latest
  governance_policy_spec_sync: quay.io/open-cluster-management/governance-policy-spec-sync:latest
  governance_policy_status_sync: quay.io/open-cluster-management/governance-policy-status-sync:latest
  governance_policy_template_sync: quay.io/open-cluster-management/governance-policy-template-sync:latest
  klusterlet_addon_controller: quay.io/open-cluster-management/klusterlet-addon-controller:latest
  klusterlet_addon_lease_controller: quay.io/open-cluster-management/klusterlet-addon-lease-controller@sha256:bed6caaa74d8f088320969073fd8e1b42ec2022ceb6b6e1c89b471c57bcc82ca
  klusterlet_addon_operator: quay.io/open-cluster-management/klusterlet-addon-operator:latest
  multicluster_operators_application: quay.io/open-cluster-management/multicluster-operators-application:latest
  multicluster_operators_channel: quay.io/open-cluster-management/multicluster-operators-channel:latest
  multicluster_operators_deployable: quay.io/open-cluster-management/multicluster-operators-deployable:latest
  multicluster_operators_placementrule: quay.io/open-cluster-management/multicluster-operators-placementrule:latest
  multicluster_operators_subscription: quay.io/open-cluster-management/multicluster-operators-subscription:latest
  multicluster_operators_subscription_release: quay.io/open-cluster-management/multicluster-operators-subscription-release:latest
  work: quay.io/open-cluster-management/work:latest
kind: ConfigMap
metadata:
  labels:
    ocm-configmap-type: image-manifest
    ocm-release-version: 2.3.0
  name: mch-image-manifest
  namespace: open-cluster-management
