# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
data:
  application_ui: quay.io/stolostron/application-ui@sha256:5c33471e7db278a03291288c582efc143444ca2e8fff0b5b1eec54481913ea87
  application_ui_tests: quay.io/stolostron/application-ui-tests@sha256:bbe3c9e2f690da73a8ffed7acc5bdafd30b3c4d939b1e1a24c06158455ce6d6a
  applifecycle_backend_e2e: quay.io/stolostron/applifecycle-backend-e2e@sha256:91763b99c8c70edc6461275d3c0a9cb49736330524bdba97ab05aab72e883b8e
  cert_manager_acmesolver: quay.io/stolostron/cert-manager-acmesolver@sha256:ba5489ce994919b1a4a8e8984e361fce3ade27ae6cd67c9b1eebc9b72434deee
  cert_manager_cainjector: quay.io/stolostron/cert-manager-cainjector@sha256:71c29fbefe15dac137293fe239c78e0ea9ddde2653cdd8b2428b8451c4bba6f1
  cert_manager_controller: quay.io/stolostron/cert-manager-controller@sha256:70282476acb991053e71d6afcdb081aab184fe5fc71cd38808daa1979085f883
  cert_manager_webhook: quay.io/stolostron/cert-manager-webhook@sha256:7bbbc966ec465ba83d6a7b52768f91e570f19ec4fa3f5d717575c28bef00b806
  cert_policy_controller: quay.io/stolostron/cert-policy-controller@sha256:55b19966eb6dc7e7780581abad6e276f4884a74700f2d699c72f2a7b8c41b7df
  cluster_curator_controller: quay.io/stolostron/cluster-curator-controller@sha256:ed0391ccaff7589e7c46cab1047dfdfb35132bad190b26c16c6bafb1de14f31a
  cluster_lifecycle_e2e: quay.io/stolostron/cluster-lifecycle-e2e@sha256:e829e61189ce340779f9c977e767bd0d0004794f88a06b0be42927592c723a73
  clusterlifecycle_state_metrics: quay.io/stolostron/clusterlifecycle-state-metrics@sha256:43eec8d3e5966cf95c3656f3303494041ee7fd6f7da4fc0b2dab667e6c3f8517
  config_policy_controller: quay.io/stolostron/config-policy-controller@sha256:6ec6a43685ca0bdc6a4b8689b106fd10a0137e6973f08f9154d6bb2bb261ae36
  configmap_watcher: quay.io/stolostron/configmap-watcher@sha256:f91f9730e0046943e4c1804734bdc679d3d096c0e4d0104d9da5bd02d4d81b33
  console: quay.io/stolostron/console@sha256:2e98361383bd3893e8a22d1ef5755524528ed0fd642255b04f8e87e3cf935cbb
  console_api: quay.io/stolostron/console-api@sha256:d4f2040761b96418664236799599c85de004756e524c2c6a1cd263980fa0e8f5
  console_header: quay.io/stolostron/console-header@sha256:dba0e9667a531330ce08963d3d20951e507c65f02d23067fe02a85f9f023f301
  discovery_operator: quay.io/stolostron/discovery-operator@sha256:dfcf5d83412fc604ee3236677306ca708fea5c0e5b6d308dfac497fb2b3e02b7
  discovery_operator_tests: quay.io/stolostron/discovery-operator-tests@sha256:316ad17829b951118f73b71907d2299fb49e884072e85165fa97839d087ae801
  endpoint_component_operator: quay.io/stolostron/endpoint-component-operator@sha256:1a8bd60538833d4dfda958cfbb18dce7c0dd99536005bc9e0545a06501ac080a
  endpoint_monitoring_operator: quay.io/stolostron/endpoint-monitoring-operator@sha256:7699af6bda905c7d21306609f111ec8f4da1cfcb61be363ab99899f72a27418d
  endpoint_operator: quay.io/stolostron/endpoint-operator@sha256:16ba86ac7c231463a081e58190c18ebc306365ed89368a3b1d47bd603b846025
  governance_policy_propagator: quay.io/stolostron/governance-policy-propagator@sha256:8889cbea528707b6b978dc84811b1ba90de6cef47516d62364e6368ad9a82de8
  governance_policy_spec_sync: quay.io/stolostron/governance-policy-spec-sync@sha256:a53a3421c66f757384ca78927c5e35580f8d522feeab58c842f61f7a102c18ea
  governance_policy_status_sync: quay.io/stolostron/governance-policy-status-sync@sha256:1e2344ba71cab3e2c017dea3d326314015531a646189d136ddccd83a20a0f082
  governance_policy_template_sync: quay.io/stolostron/governance-policy-template-sync@sha256:ba5e5e318bfd279143f4b13458dba55afd0691f641ff85592b31ab76d41808ae
  grafana: quay.io/stolostron/grafana@sha256:4ff351395090f1e5dbe765b85689919a42da9d103387594e9c4e95dcbe72474d
  grafana_dashboard_loader: quay.io/stolostron/grafana-dashboard-loader@sha256:640f59ef99449766a97eec2c7e7c2cb7f309ddf674decdf34d84c6e7b4e5f85a
  grc_policy_framework_tests: quay.io/stolostron/grc-policy-framework-tests@sha256:0594a3922570851b7acdd94cb99f5a6affb81172cf24f9de7810b3df36aaee5a
  grc_ui: quay.io/stolostron/grc-ui@sha256:56c8db012170648ca8ad4be0a89f2fa099c3485e25d74d53956e0ff1b1b88b15
  grc_ui_api: quay.io/stolostron/grc-ui-api@sha256:5bb62bd8adc8d022895c61926539d28e130487997c8a3c5906407d949b3eb0ee
  grc_ui_tests: quay.io/stolostron/grc-ui-tests@sha256:791352ffaef5c471f4b21da48c985561f92fcbe8fdafe4c44786448091cc3df8
  helloworld: quay.io/stolostron/helloworld@sha256:9e5415866dbc7f8ed82696aa2e199df7176492d42395f8d97752505ca4370f44
  iam_policy_controller: quay.io/stolostron/iam-policy-controller@sha256:faaacd6dc9954409d34f486a83a9a460ddaa13adc154e3c04237bb8797482563
  klusterlet_addon_controller: quay.io/stolostron/klusterlet-addon-controller@sha256:d4da97d8fbbf2c2402708553f7b36981884f2791e5b0c4522c3f1143e2447a4a
  klusterlet_addon_lease_controller: quay.io/stolostron/klusterlet-addon-lease-controller@sha256:bed6caaa74d8f088320969073fd8e1b42ec2022ceb6b6e1c89b471c57bcc82ca
  klusterlet_addon_operator: quay.io/stolostron/klusterlet-addon-operator@sha256:0208d99103a4e5e2c379f3c113dbdb546379d7e7b8c08e0a852844c4075dffa8
  kui_web_terminal: quay.io/stolostron/kui-web-terminal@sha256:8b7d388e6046cd08ac0645a289347e5dd93f1408857da0f0ef8afb2583063272
  kui_web_terminal_tests: quay.io/stolostron/kui-web-terminal-tests@sha256:05cc298055fc67f93e84f8a8a7e6535ff95722ad2a9d2da0fa1dce8a01caa71e
  managedcluster_import_controller: quay.io/stolostron/managedcluster-import-controller@sha256:858d4d442b89d5ac9e3823f23b7ec9eb3f9cfc09595cd24ff95019abd56d3648
  management_ingress: quay.io/stolostron/management-ingress@sha256:206243b52f727850644bda1c9d24b338d6f375012f056ec6a80c8458c25f16df
  metrics_collector: quay.io/stolostron/metrics-collector@sha256:dbb1e130dacc095cc1aef3336259181ade133a79592e3863b0578974ece5cd16
  multicloud_manager: quay.io/stolostron/multicloud-manager@sha256:d6d9385352d9d32d1db184dd1ba72dc1afe52904b240317e4a4fe60d56579b48
  multicluster_observability_operator: quay.io/stolostron/multicluster-observability-operator@sha256:ccdc8607aa144250357b15a72d4ff8445f001251f7cac4426e4b9809e1a8a0a7
  multicluster_operators_application: quay.io/stolostron/multicluster-operators-application@sha256:abefd85d18f9b90782ca5d4ccfd6e30d72d6a6c2387a5296d74f31373c2ddbc5
  multicluster_operators_channel: quay.io/stolostron/multicluster-operators-channel@sha256:aea5fac3280e4e0cbdd374e1c11e8d72c37aba3b260925a284978fa70f6b486d
  multicluster_operators_deployable: quay.io/stolostron/multicluster-operators-deployable@sha256:4c91ba2ce95b6d70295f288acec335e8f281ab6a496c2ea87f3162bfe636496b
  multicluster_operators_placementrule: quay.io/stolostron/multicluster-operators-placementrule@sha256:b1c293d6ed5cf8105e06c7fad379b574320d0aa09094d5545b13131a473dd5d4
  multicluster_operators_subscription: quay.io/stolostron/multicluster-operators-subscription@sha256:e13ec77680133e7d3b68866757b17c15676fba1002f200843af3df7eefe87e60
  multicluster_operators_subscription_release: quay.io/stolostron/multicluster-operators-subscription-release@sha256:ddf8edf3031c34b24c4e2eabded796c04dbb7e1f66ad78ab920c6f6eee917da9
  multiclusterhub_crds: quay.io/stolostron/multiclusterhub-crds@sha256:e985bd4a15bbc2b199f4ee81d907f7499f657e76b548da9a5782b986f5ff02b5
  multiclusterhub_operator: quay.io/stolostron/multiclusterhub-operator@sha256:a3cfee388c8e481e92d797ae932c2bbdf6ae91d83ece0b6fb380eb1c60203f63
  multiclusterhub_operator_tests: quay.io/stolostron/multiclusterhub-operator-tests@sha256:198c34a65b8b0fcba5da5fc5fadd42ac8b5681d5842aa1e97054ca38857c8d7f
  multiclusterhub_repo: quay.io/stolostron/multiclusterhub-repo@sha256:360c879646ae9b0e85bbe971792a12c84b32eb4a006f819fac2aaa4c41429082
  must_gather: quay.io/stolostron/must-gather@sha256:3ac3abef74bbb1ec184f8f34f46914b5f13dbd2e95a4eb99406433cf8fac9b08
  oauth_proxy: quay.io/stolostron/origin-oauth-proxy@sha256:ae1b3ad6a9e76271de5c6d16abe5586abac043da032d686d1fc78f43ed7f3606
  observability_e2e_test: quay.io/stolostron/observability-e2e-test@sha256:1ba94c4e619a0e5fdf79ba2dc1464277a25ec0059b166dc0ed6cf42693ab4693
  observatorium_operator: quay.io/stolostron/observatorium-operator@sha256:8f223213763b3e559e6fe0eca2a4d4899ae7492fb2bf5e8e7a6f88479aebe683
  openshift_hive: quay.io/openshift-hive/hive@sha256:1e5b534bbfaa7f0aef439304544aa0aee603dddb26a2e204ea2ed848193fe762
  rbac_query_proxy: quay.io/stolostron/rbac-query-proxy@sha256:01d44a2c7d8553d26ba640f3aa75ec9cb653bdb0fa5bcf369717bb5ad50c2f26
  rcm_controller: quay.io/stolostron/rcm-controller@sha256:2c96a91775105292745efee1d09dbde1e7192752b79afb9d2a150ac04d64771d
  redisgraph_tls: quay.io/stolostron/redisgraph-tls@sha256:fb3d3a3e13f81c1dbda0db197a28087f7fb2e7b295463bb6ac4f405899cfea31
  registration: quay.io/stolostron/registration@sha256:1153d9883b745f52772965185c8b571e53aa7a97faceff0db7358dc1833d6ae6
  registration_operator: quay.io/stolostron/registration-operator@sha256:c0c081e1abbb4264050509975086e807f8779eb80cfd02d868e5d0d7ac01b2e6
  search_aggregator: quay.io/stolostron/search-aggregator@sha256:2a862340d9c538a8dac5219d654f98762d0861794e6da0f39cd7c894a7af92b0
  search_api: quay.io/stolostron/search-api@sha256:3189d9ad06dd70f0e7bbe97ff48c2c9560f502cfc4e3e62fea20176c13dd514c
  search_collector: quay.io/stolostron/search-collector@sha256:fdba532c2dfbd5178631712cf2c473159f8a003ed0f9018588c1b046c7d0189b
  search_e2e: quay.io/stolostron/search-e2e@sha256:cc6daebf7acedfdf388fc07f708a083d77ba66326f9b92eed872f4a7f15f6997
  search_operator: quay.io/stolostron/search-operator@sha256:c49a4221069d7136309cd8f26bb13911d360c6f763a72d7797b4cba3392b2f37
  search_ui: quay.io/stolostron/search-ui@sha256:3a5e82ea1c3a5d2d70176c061326a74bef8b0aff760a973ffe4558f2df911a04
  submariner_addon: quay.io/stolostron/submariner-addon@sha256:4a94f6c74048d5525ea2d73dbddfde8291e768df4310fe7b7cab3f32be4c8692
  work: quay.io/stolostron/work@sha256:58f92725033424d0dfd5cf8d1c827e1cebe5403bc46f985e9a9085cd9f9732b9
kind: ConfigMap
metadata:
  labels:
    ocm-configmap-type: image-manifest
    ocm-release-version: 2.4.3
  name: mch-image-manifest
  namespace: open-cluster-management

